// This file is automatically generated. Do not edit it directly.
// Force redeploy: 2025-11-27
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const errorMsg = '❌ Error de configuración: El servidor no está configurado. Contacta al administrador.';
  console.error(errorMsg);
  console.error('Missing:', {
    SUPABASE_URL: SUPABASE_URL ? 'OK' : 'MISSING',
    SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY ? 'OK' : 'MISSING'
  });
  throw new Error(errorMsg);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);